### PR TITLE
validate node shape

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Review by alspitz — CHANGES_REQUESTED** [review]
Is resp a numpy array? It is coming back as a list on my system. Can you use the len function instead?

**Comment by alspitz** [comment]
I've pushed a change to avoid crashing in this case: https://github.com/pumaking/cpu_monitor/commit/854a39adfaab5e9050426f67fb30d38fc8d9ba63

**Comment by amilcarlucas** [comment]
Thank you. Closing this one now

**Comment by amilcarlucas** [comment]
@MikeWrockAIS the patch at https://github.com/pumaking/cpu_monitor/commit/854a39adfaab5e9050426f67fb30d38fc8d9ba63 is better than your local fix.

**Pull request closed without merging**
